# .github/workflows/build.yml

name: Build Skyrim Multiplayer Project

# This workflow runs on pushes and pull requests to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #================================#
  #       Windows Build Job        #
  #================================#
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # FIX: Use Node.js 20.x to meet new dependency requirements
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Yarn
        run: npm install --global yarn

      # The yarn install step is now handled by the CMake script itself
      - name: Configure CMake
        run: cmake -B build

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: skymp-windows-build
          path: build/dist/

  #================================#
  #        Linux Build Job         #
  #================================#
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-22.04
    container: skymp/skymp-vcpkg-deps:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # FIX: Explicitly set the compiler to help vcpkg detect the toolchain
      - name: Set Compiler Environment
        run: |
          echo "CC=clang-15" >> $GITHUB_ENV
          echo "CXX=clang++-15" >> $GITHUB_ENV

      - name: Configure with build script
        run: ./build.sh --configure -DCMAKE_BUILD_TYPE=Release

      - name: Build with build script
        run: ./build.sh --build build --parallel $(nproc)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: skymp-linux-build
          path: build/dist/
